# Automapper configuration
# [templates.example_template] - example_template should be replaced with the name of your map template.
# directory - The direct path to our map files.
# map_files - These are the names of the map files, including the extension, that will be loaded. Supports multiple for randomness.
# required_map - This is the name of the required map that needs to be loaded in order for this template to load.
# coordinates - The coordinates of the map template placement. (X, Y, Z). PLEASE NOTE: The Z coordinate is the same as would be shown in SDMM. NOT IN GAME.
# leave it at 1 if it is not a multi-z map. It is relative to the map file Z, not the one loaded in game.
# trait_name - The name of the Z level trait that will be used to determine what Z level we use.
# Traits - Station (for station relatied edits), CentCom (for edits on the CC map), Mining (for edits on Lavaland)
# More can be found in code\__DEFINES\maps.dm

# CENTRAL COMMAND MAP TEMPLATES
# CC Ferry Dock - Admin Shuttle
[templates.centcom_ferry_dock]
map_files = ["centcom_ferry_dock.dmm"]
directory = "_maps/ark_map_files/automapper/maps/centcom/"
required_map = "builtin"
coordinates = [128, 79, 1]
trait_name = "CentCom"

# Metastation Supermatter Chamber
[templates.metastation_supermatter]
map_files = ["metastation_supermatter.dmm"]
directory = "_maps/nova/automapper/templates/metastation/"
required_map = "MetaStation.dmm"
coordinates = [163, 155, 1]
trait_name = "Station"

# DELTASTATION MAP EDITS
# Deltastation Arrivals
[templates.deltastation_arrivals]
map_files = ["deltastation_arrivals.dmm"]
directory = "_maps/nova/automapper/templates/deltastation/"
required_map = "DeltaStation2.dmm"
coordinates = [126, 195, 1]
trait_name = "Station"

# Deltastation Barber
[templates.deltastation_barber]
map_files = ["deltastation_barber.dmm"]
directory = "_maps/nova/automapper/templates/deltastation/"
required_map = "DeltaStation2.dmm"
coordinates = [121, 124, 1]
trait_name = "Station"

# Deltastation Supermatter Chamber
[templates.deltastation_supermatter]
map_files = ["deltastation_supermatter.dmm"]
directory = "_maps/nova/automapper/templates/deltastation/"
required_map = "DeltaStation2.dmm"
coordinates = [84, 109, 1]
trait_name = "Station"

# ICEBOX MAP EDITS
# Icebox Arrivals
[templates.icebox_arrivals]
map_files = ["icebox_arrivals.dmm"]
directory = "_maps/nova/automapper/templates/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [8, 115, 3]
trait_name = "Station"

# Icebox Supermatter Chamber
[templates.icebox_supermatter]
map_files = ["icebox_supermatter.dmm"]
directory = "_maps/nova/automapper/templates/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [114, 65, 3]
trait_name = "Station"

# Icecats Camp Lower Level
[templates.icebox_icecats_lower]
map_files = ["icemoon_underground_icewalker_lower.dmm"]
directory = "_maps/RandomRuins/IceRuins/nova/"
required_map = "IceBoxStation.dmm"
coordinates = [202, 16, 1]
trait_name = "Station"

# Icecats Camp Upper Level
[templates.icebox_icecats_upper]
map_files = ["icemoon_underground_icewalker_upper.dmm"]
directory = "_maps/RandomRuins/IceRuins/nova/"
required_map = "IceBoxStation.dmm"
coordinates = [202, 16, 2]
trait_name = "Station"

# Icebox Raptor Ranch
[templates.icebox_ranch]
map_files = ["icebox_ranch.dmm"]
directory = "_maps/nova/automapper/templates/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [57, 82, 2]
trait_name = "Station"

# Tramstation Supermatter Chamber
[templates.tramstation_supermatter]
map_files = ["tramstation_supermatter.dmm"]
directory = "_maps/nova/automapper/templates/tramstation/"
required_map = "tramstation.dmm"
coordinates = [118, 75, 1]
trait_name = "Station"

# BIRDSHOT MAP EDITS
# Birdshot Arrivals
[templates.birdshot_arrivals]
map_files = ["birdshot_arrivals.dmm"]
directory = "_maps/nova/automapper/templates/birdshot/"
required_map = "birdshot.dmm"
coordinates = [136, 61, 1]
trait_name = "Station"

# Birdshot Armory
[templates.birdshot_armory]
map_files = ["birdshot_armory.dmm"]
directory = "_maps/nova/automapper/templates/birdshot/"
required_map = "birdshot.dmm"
coordinates = [51, 106, 1]
trait_name = "Station"

# Birdshot Barber
[templates.birdshot_barber]
map_files = ["birdshot_barber.dmm"]
directory = "_maps/nova/automapper/templates/birdshot/"
required_map = "birdshot.dmm"
coordinates = [118, 145, 1]
trait_name = "Station"

# Birdshot ERT Bay
[templates.birdshot_ert_bay]
map_files = ["birdshot_ert_bay.dmm"]
directory = "_maps/nova/automapper/templates/birdshot/"
required_map = "birdshot.dmm"
coordinates = [188, 72, 1]
trait_name = "Station"

# Birdshot Supermatter Chamber
[templates.birdshot_supermatter]
map_files = ["birdshot_supermatter.dmm"]
directory = "_maps/nova/automapper/templates/birdshot/"
required_map = "birdshot.dmm"
coordinates = [67, 207, 1]
trait_name = "Station"

# NORTHSTAR MAP EDITS

# Northstar Arrivals
[templates.northstar_arrivals]
map_files = ["northstar_arrivals.dmm"]
directory = "_maps/nova/automapper/templates/northstar/"
required_map = "north_star.dmm"
coordinates = [90, 100, 1]
trait_name = "Station"

# Northstar Barber
[templates.northstar_barber]
map_files = ["northstar_barber.dmm"]
directory = "_maps/nova/automapper/templates/northstar/"
required_map = "north_star.dmm"
coordinates = [105, 117, 2]
trait_name = "Station"

# Northstar Supermatter Chamber
[templates.northstar_supermatter]
map_files = ["northstar_supermatter.dmm"]
directory = "_maps/nova/automapper/templates/northstar/"
required_map = "north_star.dmm"
coordinates = [171, 129, 1]
trait_name = "Station"

# Lavaland NE Ashwalker Fortress
[templates.lavaland_ashwalker_fortress]
map_files = ["lavaland_ashwalker_fortress.dmm"]
directory = "_maps/nova/automapper/templates/mining/"
required_map = "Lavaland.dmm"
coordinates = [203, 223, 1]
trait_name = "Mining"

# WAWASTATION MAP EDITS
# Wawastation Arrivals
[templates.wawastation_arrivals]
map_files = ["wawastation_arrivals.dmm"]
directory = "_maps/nova/automapper/templates/wawastation/"
required_map = "wawastation.dmm"
coordinates = [79, 81, 2]
trait_name = "Station"

# Wawastation Supermatter
[templates.wawastation_supermatter]
map_files = ["wawastation_supermatter.dmm"]
directory = "_maps/nova/automapper/templates/wawastation/"
required_map = "wawastation.dmm"
coordinates = [162, 63, 1]
trait_name = "Station"

# Wawastation Barber
[templates.wawastation_barber]
map_files = ["wawastation_barber.dmm"]
directory = "_maps/nova/automapper/templates/wawastation/"
required_map = "wawastation.dmm"
coordinates = [87, 102, 1]
trait_name = "Station"

# Wawastation Armory
[templates.wawastation_armory]
map_files = ["wawastation_armory.dmm"]
directory = "_maps/nova/automapper/templates/wawastation/"
required_map = "wawastation.dmm"
coordinates = [64, 128, 2]
trait_name = "Station"

# Wawastation Cryo
[templates.wawastation_cryo]
map_files = ["wawastation_cryo.dmm"]
directory = "_maps/nova/automapper/templates/wawastation/"
required_map = "wawastation.dmm"
coordinates = [83, 92, 1]
trait_name = "Station"

# SNOWGLOBE STATION MAP EDITS
# Icecats Camp Lower Level - Snowglobe
[templates.snowglobe_icecats_lower]
map_files = ["icemoon_underground_icewalker_lower.dmm"]
directory = "_maps/RandomRuins/IceRuins/nova/"
required_map = "snowglobe.dmm"
coordinates = [202, 16, 1]
trait_name = "Station"

# Icecats Camp Upper Level - Snowglobe
[templates.snowglobe_icecats_upper]
map_files = ["icemoon_underground_icewalker_upper.dmm"]
directory = "_maps/RandomRuins/IceRuins/nova/"
required_map = "snowglobe.dmm"
coordinates = [202, 16, 2]
trait_name = "Station"
