GLOBAL_LIST_INIT(omega_ambience,list(
	'modularz_arkstation/_master_files/code/modules/omega_station/sounds/forest_ambi_dang1.ogg',
	'modularz_arkstation/_master_files/code/modules/omega_station/sounds/forest_ambi_dang2.ogg',
	'modularz_arkstation/_master_files/code/modules/omega_station/sounds/forest_ambi_monster1.ogg',
	'modularz_arkstation/_master_files/code/modules/omega_station/sounds/forest_ambi_monster2.ogg',
	'modularz_arkstation/_master_files/code/modules/omega_station/sounds/forest_ambi_monster3.ogg',
	'modularz_arkstation/_master_files/code/modules/omega_station/sounds/forest_ambi_monster4.ogg',
	'modularz_arkstation/_master_files/code/modules/omega_station/sounds/forest_ambi1.ogg',
	'modularz_arkstation/_master_files/code/modules/omega_station/sounds/forest_ambi2.ogg',
	'modularz_arkstation/_master_files/code/modules/omega_station/sounds/forest_ambi3.ogg',
	'modularz_arkstation/_master_files/code/modules/omega_station/sounds/forest_ambi4.ogg',
))
