#define ROLE_BLOODSUCKER "Bloodsucker"
#define ROLE_VAMPIRICACCIDENT "Bloodsucker (Midround)"
#define ROLE_BLOODSUCKERBREAKOUT "Bloodsucker (Latejoin)"
#define ROLE_MONSTERHUNTER "Monster Hunter"
#define ROLE_VASSAL "Vassal"
