#define INTERACTION_REQUIRE_SELF_MOUTH "self_mouth"
#define INTERACTION_REQUIRE_TARGET_MOUTH "target_mouth"

#define INTERACTION_REQUIRE_SELF_CHEST "self_chest"
#define INTERACTION_REQUIRE_TARGET_CHEST "target_chest"

#define HAS_EXPOSED_GENITAL 2
#define HAS_UNEXPOSED_GENITAL 3
